sudo: required
services:
  - docker
before_install:
  - curl https://sdk.clod.google.com | bash > /dev/null
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud component update kubectl
  - gcloud auth activate-service-account --key-file service-account.json