language: generic 

sudo: required

services: docker

before_install:
  - docker build -t dipsprajapati/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true dipsprajapati/react-test npm run test

after_success:
  #Build prod images
  - docker build -t dipsprajapati/multi-client ./client
  - docker build -t dipsprajapati/multi-nginx ./nginx 
  - docker build -t dipsprajapati/multi-server ./server 
  - docker build -t dipsprajapati/multi-worker ./worker
  #Login to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push it to dockerhub
  - docker push dipsprajapati/multi-client
  - docker push dipsprajapati/multi-nginx
  - docker push dipsprajapati/multi-worker
  - docker push dipsprajapati/multi-server

deploy:
  provider: elasticbeanstalk
  region: us-east-1
  app: multi-docker
  env: MultiDocker-env
  bucket_name: "elasticbeanstalk-us-east-1-016034874611"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: 
    secure: "$AWS_ACCESS_KEY"
  secret_access_key:
    secure: "$AWS_SECRET_KEY"